module.exports = {
  "code": 0,
  "message": "成功请求",
  "data": [{
    "lanmu_id": 0,
    "lanmu_name": "首页",
    "lanmu_order": 0,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/pages/news/index"
  } , {
    "lanmu_id": 1,
    "lanmu_name": "我的男孩",
    "lanmu_order": 0,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/pages/dogs?t=1"
  }, {
    "lanmu_id": 32,
    "lanmu_name": "我的女孩",
    "lanmu_order": 1,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/pages/dogs?t=2"
  },{
      "lanmu_id": 61,
      "lanmu_name": "地中海大家族",
      "lanmu_order": 3,
      "lanmu_menu": 1,
      "lanmu_custom": 0,
      "lanmu_json": "/pages/dogs?t=4"
    },{
    "lanmu_id": 59,
    "lanmu_name": "待售犬只",
    "lanmu_order": 2,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/pages/dogs?t=3"
  }, {
    "lanmu_id": 13,
    "lanmu_name": "明日之星",
    "lanmu_order": 4,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/pages/dogs?t=5"
  }, {
    "lanmu_id": 30,
    "lanmu_name": "实时资讯",
    "lanmu_order": 5,
    "lanmu_menu": 0,
    "lanmu_custom": 1,
    "lanmu_json": "/pages/article/index"
    }, {
      "lanmu_id": 111,
      "lanmu_name": "赏历墙",
      "lanmu_order": 8,
      "lanmu_menu": 0,
      "lanmu_custom": 1,
      "lanmu_json": "/pages/wall/index"
    }, {
    "lanmu_id": 2,
    "lanmu_name": "犬种知识",
    "lanmu_order": 6,
    "lanmu_menu": 1,
    "lanmu_custom": 1,
    "lanmu_json": "/pages/knowledge/index"
  }, {
    "lanmu_id": 70,
    "lanmu_name": "片花",
    "lanmu_order": 7,
    "lanmu_menu": 0,
    "lanmu_custom": 1,
    "lanmu_json": "/pages/video/index"
  }, {
    "lanmu_id": 12,
    "lanmu_name": "联系我们",
    "lanmu_order": 9,
    "lanmu_menu": 0,
    "lanmu_custom": 1,
    "lanmu_json": "/pages/contacts/index"
  }],
  "updateDime": 1471398874
}